### ISSUE TITLE
[MicroBoard] Error raised after re-executing the code

### ISSUE THREAD

**Issue by yeyeto2788** [yeyeto2788/MicroPythonScripts#5]
After successfully running the code for the first time, then upload changes on the code and error is raised on the part of the code from the [**`MicroBoard/releases/MicroBoard.py`**](https://github.com/yeyeto2788/MicroPythonScripts/blob/master/MicroBoard/Release/MicroBoard.py) file in the `s.bind(addr)` method call.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "MicroBoard.py", line 109, in <module>
  File "MicroBoard.py", line 88, in main
OSError: [Errno 98] EADDRINUSE
```

It might be due to not resetting the AP when the script starts.

More investigation is needed in order to clarify a possible solution in here.

**More info:**

```
>>> import os
>>> os.uname()
(sysname='esp8266', nodename='esp8266', release='2.0.0(5a875ba)', version='v1.9.3-8-g63826ac5c on 2017-11-01', machine='ESP module with ESP8266')
```

**Comment by yeyeto2788** [comment]
Error being discussed on https://github.com/micropython/micropython/issues/3739

Also on MicroPython [documentation ](http://docs.micropython.org/en/latest/esp8266/library/usocket.html#usocket.socket.bind) it states the following:
>The socket must not already be bound.

The hard-reset option would be the first possible solution
